### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by popey** [snapcrafters/thelounge#1]
Seems this fails to build. 

```
Downloading 'latest.tar.gz'  96%                                               
Downloading 'latest.tar.gz'  97%                                               
Downloading 'latest.tar.gz'  98%                                               
Downloading 'latest.tar.gz' 100%                                               
Downloading 'latest.tar.gz' 100%                                               
/build/86a907fed41c0f1e9658abf01b9fec68-xenial/parts/thelounge/npm/bin/yarn --proxy http://snap-proxy.launchpad.net:3128 --https-proxy http://snap-proxy.launchpad.net:3128 run build
Failed to run '/build/86a907fed41c0f1e9658abf01b9fec68-xenial/parts/thelounge/npm/bin/yarn --proxy http://snap-proxy.launchpad.net:3128 --https-proxy http://snap-proxy.launchpad.net:3128 run build' for 'thelounge': Exited with code 1.
Verify that the part is using the correct parameters and try again.
Build failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/build_snap.py", line 269, in run
    self.pull()
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/build_snap.py", line 221, in pull
    env=env)
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/build_snap.py", line 103, in run_build_command
    return self.backend.run(args, cwd=cwd, env=full_env, **kwargs)
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/lxd.py", line 456, in run
    subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['lxc', 'exec', 'lp-xenial-i386', '--env', 'LANG=C.UTF-8', '--env', 'SHELL=/bin/sh', '--env', 'SNAPCRAFT_LOCAL_SOURCES=1', '--env', 'SNAPCRAFT_SETUP_CORE=1', '--env', 'SNAPCRAFT_BUILD_INFO=1', '--env', 'SNAPCRAFT_IMAGE_INFO={"build_url": "https://snap-proxy.launchpad.net:3128', '--env', 'https_proxy=http://snap-proxy.launchpad.net:3128', '--env', 'GIT_PROXY_COMMAND=/usr/local/bin/snap-git-proxy', '--', '/bin/sh', '-c', 'cd /build/86a907fed41c0f1e9658abf01b9fec68-xenial && linux32 snapcraft pull']' returned non-zero exit status 2
```

https://launchpadlibrarian.net/370542429/buildlog_snap_ubuntu_xenial_i386_86a907fed41c0f1e9658abf01b9fec68-xenial_BUILDING.txt.gz

**Comment by sergiusens** [comment]
I will need to look into this

**Comment by lucyllewy** [comment]
The error was (is?) further up from the snipped @popey posted in the first message:

```plain
Downloading 'latest.tar.gz'   1%                                               
yarn run v1.6.0
$ webpack
/bin/sh: 1: webpack: not found
error Command failed with exit code 127.
```

I believe this is because snapcraft isn't executing `yarn` to install the dependencies before running `yarn build`.
